name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3
    - run: go vet ./...
    - run: go build
    - run: go test ./...
